# Generated by Django 4.0.1 on 2022-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_job',
            name='learning_rate',
            field=models.FloatField(default=1e-05, verbose_name='learning_rate'),
        ),
        migrations.AlterField(
            model_name='training_job',
            name='num_epochs',
            field=models.IntegerField(default=2, verbose_name='num_epochs'),
        ),
        migrations.AlterField(
            model_name='training_job',
            name='per_gpu_batch_size',
            field=models.IntegerField(default=10, verbose_name='per_gpu_batch_size'),
        ),
    ]
